# Generated by Django 5.2.8 on 2025-11-29 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(help_text='Ex: Listas, Joins, API Rest', max_length=100, verbose_name='Conteúdo')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora Início')),
                ('tempo_liquido', models.DurationField(help_text='Formato HH:MM:SS (Ex: 01:30:00)')),
                ('qtd_exercicios', models.IntegerField(blank=True, default=0, verbose_name='Qtd. Exercícios')),
                ('qtd_acertos', models.IntegerField(blank=True, default=0, verbose_name='Qtd. Acertos')),
                ('anotacoes', models.TextField(blank=True, verbose_name='Diário de Bordo (Markdown)')),
                ('metodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.metodoestudo', verbose_name='Método')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tecnologia', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Sessão de Estudo',
                'verbose_name_plural': 'Sessões de Estudo',
                'ordering': ['-data_registro'],
            },
        ),
    ]
