# Generated by Django 5.2.8 on 2025-11-30 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessaoestudo',
            options={'ordering': ['-data_registro']},
        ),
        migrations.AlterField(
            model_name='sessaoestudo',
            name='tempo_liquido',
            field=models.DurationField(help_text='Formato HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='sessaoestudo',
            name='topico',
            field=models.CharField(max_length=100, verbose_name='Conteúdo'),
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('tempo', 'Tempo Total'), ('tecnologia', 'Especialista em Tecnologia'), ('metodo', 'Mestre do Método'), ('streak', 'Ofensiva')], max_length=20)),
                ('tipo_visual', models.CharField(choices=[('padrao', 'Círculo Padrão'), ('hexagono', 'Hexágono (Desafio)')], default='padrao', max_length=20)),
                ('quantidade_necessaria', models.IntegerField()),
                ('xp_reward', models.IntegerField(default=100)),
                ('icone_fa', models.CharField(default='fas fa-trophy', max_length=50)),
                ('cor_hex', models.CharField(default='#f1c40f', max_length=7)),
                ('tecnologia_alvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=1)),
                ('conquistas', models.ManyToManyField(blank=True, to='core.conquista')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
