# Generated by Django 5.2.8 on 2025-11-30 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sessaoestudo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquista',
            name='metodo_alvo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.metodoestudo'),
        ),
    ]
