# Generated by Django 5.2.8 on 2025-11-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conquista_metodo_alvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquista',
            name='oculta',
            field=models.BooleanField(default=False, help_text='Quando marcada, só aparece após desbloquear.'),
        ),
    ]
