# Generated by Django 5.2.8 on 2025-11-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conquista_oculta'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sessaoestudo',
            index=models.Index(fields=['data_registro'], name='core_sessao_data_re_bfb56a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaoestudo',
            index=models.Index(fields=['tecnologia'], name='core_sessao_tecnolo_ba9df6_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaoestudo',
            index=models.Index(fields=['metodo'], name='core_sessao_metodo__46fa01_idx'),
        ),
    ]
