# Generated by Django 5.2.8 on 2025-11-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sessaoestudo_core_sessao_data_re_bfb56a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_mensal',
            field=models.IntegerField(default=0, help_text='Meta em horas'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_semanal',
            field=models.IntegerField(default=0, help_text='Meta em horas'),
        ),
    ]
