# Generated by Django 5.2.8 on 2025-11-30 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfilusuario_meta_mensal_perfilusuario_meta_semanal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BossBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('xp_reward', models.IntegerField(default=500)),
                ('boss_icon', models.CharField(default='fas fa-dragon', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FRAME', 'Moldura Avatar'), ('BANNER', 'Banner Perfil'), ('THEME', 'Tema UI')], max_length=20)),
                ('price', models.IntegerField(default=100)),
                ('image_url', models.URLField(blank=True)),
                ('css_class', models.CharField(blank=True, help_text='Classe CSS para aplicar o estilo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sos_requested', models.BooleanField(default=False, help_text='Pedir ajuda para a comunidade?')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bossbattle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BUG', '🐛 Clérigo (Bug Fix)'), ('OPTIMIZE', '⚡ Ferreiro (Otimização)'), ('STYLE', '🎨 Bardo (Estilo)')], max_length=20)),
                ('content', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.projectsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-code', help_text='Classe FontAwesome', max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.skillnode')),
            ],
            options={
                'verbose_name': 'Nó de Habilidade',
                'verbose_name_plural': 'Árvore de Habilidades',
            },
        ),
        migrations.CreateModel(
            name='JobQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('salary', models.CharField(max_length=50)),
                ('min_level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('required_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.skillnode')),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('method', models.CharField(choices=[('VIDEO', 'Vídeo Aula (1.0x)'), ('READING', 'Leitura/Docs (1.2x)'), ('CODING', 'Codificação (1.5x)'), ('PROJECT', 'Projeto Prático (2.0x)')], default='VIDEO', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(default=0, editable=False)),
                ('xp_earned', models.IntegerField(default=0, editable=False)),
                ('coins_earned', models.IntegerField(default=0, editable=False)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.skillnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(blank=True, to='core.storeitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Nível')),
                ('current_xp', models.IntegerField(default=0, verbose_name='XP Atual')),
                ('total_xp', models.IntegerField(default=0, verbose_name='XP Total')),
                ('dev_coins', models.IntegerField(default=0, verbose_name='DevCoins')),
                ('github_link', models.URLField(blank=True, verbose_name='Link GitHub')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('equipped_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_bannered', to='core.storeitem', verbose_name='Banner Equipado')),
                ('equipped_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_framed', to='core.storeitem', verbose_name='Moldura Equipada')),
                ('skills_desbloqueadas', models.ManyToManyField(blank=True, related_name='usuarios', to='core.skillnode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Gamer',
                'verbose_name_plural': 'Perfis Gamer',
            },
        ),
    ]
