# Generated by Django 5.2.8 on 2025-11-30 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bossbattle_storeitem_projectsubmission_codereview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-medal', max_length=50)),
                ('xp_bonus', models.IntegerField(default=100)),
                ('coin_bonus', models.IntegerField(default=50)),
                ('is_secret', models.BooleanField(default=False, help_text='Se true, só aparece quando ganha')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='Streak Atual'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_checkin',
            field=models.DateField(blank=True, null=True, verbose_name='Último Check-in'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longest_streak',
            field=models.IntegerField(default=0, verbose_name='Maior Streak'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_freezes',
            field=models.IntegerField(default=0, verbose_name='Congeladores'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.badge')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user_profile', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, through='core.UserBadge', to='core.badge'),
        ),
    ]
