# Generated by Django 5.2.8 on 2025-11-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_badge_userprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossbattle',
            name='min_skill_level',
            field=models.IntegerField(default=1, help_text='Nível necessário na Skill para desbloquear'),
        ),
        migrations.AddField(
            model_name='bossbattle',
            name='recommended_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bosses', to='core.skillnode'),
        ),
    ]
