# Generated by Django 5.2.8 on 2025-11-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bossbattle_min_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossbattle',
            name='coin_reward',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='bossbattle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
