# Generated by Django 5.2.8 on 2025-11-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bossbattle_coin_reward_bossbattle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossbattle',
            name='boss_image',
            field=models.CharField(blank=True, help_text='Nome do arquivo na pasta boss_img/', max_length=200),
        ),
        migrations.AddField(
            model_name='bossbattle',
            name='medal_image',
            field=models.CharField(blank=True, help_text='Nome do arquivo da medalha na pasta boss_img/', max_length=200),
        ),
    ]
